# Symlink to this file from ~/.zshrc
# You should also symlink ~/.zshenv to zsh/env in this directory
export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/Developer/usr/bin:$PATH

. ~/bin/dotfiles/zsh/config
. ~/bin/dotfiles/zsh/aliases
. ~/bin/dotfiles/zsh/colors

# export GREP_OPTIONS=' --color=auto'
# export CLICOLOR=1
#
# export PATH="$HOME/.rbenv/bin:$PATH"
# eval "$(rbenv init -)"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
export PATH=$HOME/.rbenv/bin:$PATH
